### ISSUE TITLE
Mysql2::Error when migrating

### ISSUE THREAD

**Issue by jonhue** [charlotte-ruby/impressionist#236] opened 2017-03-10 16:24 UTC
> Mysql2::Error: BLOB/TEXT column 'params' used in key specification without a key length: CREATE  INDEX `poly_params_request_index`  ON `impressions` (`impressionable_type`, `impressionable_id`, `params`)
c:/Users/Jonas/gitapps/slooob/db/migrate/20170309181527_create_impressions_table.rb:25:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: BLOB/TEXT column 'params' used in key specification without a key length: CREATE  INDEX `poly_params_request_index`  ON `impressions` (`impressionable_type`, `impressionable_id`, `params`)
c:/Users/Jonas/gitapps/slooob/db/migrate/20170309181527_create_impressions_table.rb:25:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Mysql2::Error: BLOB/TEXT column 'params' used in key specification without a key length
c:/Users/Jonas/gitapps/slooob/db/migrate/20170309181527_create_impressions_table.rb:25:in `up'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by twist900** [comment] 2017-03-19 19:30
Confirm, I get the same error.

**Comment by invalidusrname** [comment] 2017-03-21 02:27
This looks like a duplicate of #222. It's been fixed as of #228. Until this gets a new release, you can set your Gemfile to use 

    gem 'impressionist', git: 'https://github.com/charlotte-ruby/impressionist.git'

**Closed by invalidusrname** 2017-03-21 02:27 UTC
