### ISSUE TITLE
impressionist not work in rails 5

### ISSUE THREAD

**Issue by Qasem-h** [charlotte-ruby/impressionist#219] opened 2016-09-16 13:20 UTC
Hello
impressionist gem not work in rails 5
any update to rails  5 ?

**Comment by johnmcaliley** [comment] 2016-09-16 13:51
I just updated the gem and pushed a new version.  Can up update the gem in your app and see if it works now?  There is one other pull request to allow better compatibility with rails 5 that I will be merging in the next day or 2 if this latest version doesn't fix it for you.

**Comment by Qasem-h** [comment] 2016-09-16 14:56
@johnmcaliley  Thanks for reply 
 I tested new version but still not work 

Controller :

```
def show
   @video = Video.find(params[:id])
   impressionist(@video)
```
Model :

```
  # include Impressionist::IsImpressionable 
  is_impressionable :counter_cache => true, :column_name => :views

```

Views : 
`<%= impressionist_count(:filter=>:ip_address) %>`
or 
`<%= impressionist(:filter=>:ip_address).count %>`

I got this error : 

**unknown attribute 'params' for Impression.**

I used this gems : 
```
gem 'friendly_id'  # Just for save title slug in database 
gem "acts_as_hashids" # for unique IDs
```

**Comment by adeelberlin** [comment] 2016-09-18 10:43
Hi,

I am also having this issue think it has to do something with the new update not sure. This was working fine before.

**Comment by Qasem-h** [comment] 2016-09-20 00:17
@johnmcaliley  any update  !?

**Comment by rocket4ce** [comment] 2016-09-21 04:47
Hi, I have same issue, unknown attribute 'params' for Impression. :/

**Comment by johnmcaliley** [comment] 2016-09-26 13:22
I'm looking into this today.  Is everyone seeing the issue with postgres or are you seeing it with other DBs like mysql?

**Comment by johnmcaliley** [comment] 2016-09-26 13:49
I see what the problem is now.  One of the pull requests I merged added a new feature where a "params" column was added.  The pull request did not include a migration file for this, so if you are upgrading an existing app with the latest version of impressionist, then the new column will be missing from the Impressions table.  @rocket4ce I think the reason you are not seeing this from sqlite is probably because you regenerated the database.  For those of you having issues, you will need to create a new rails migration file and add this code to create the new column and index:

` 
add_column :impressions, :params, :text

add_index :impressions, [:impressionable_type, :impressionable_id, :params], :name => "poly_params_request_index", :unique => false
end
`

Let me know if this solves it and I will figure out how to make it work seamlessly with the next upgrade.

**Comment by nickcoyne** [comment] 2016-09-28 00:47
@johnmcaliley that works, but I had to limit the  params index length, eg.
```
add_index :impressions, [:impressionable_type, :impressionable_id, :params], name: 'poly_params_request_index', unique: false, length: { params: 100 }
```

**Comment by atomn** [comment] 2016-09-29 09:01
yep, works!

**Comment by Qasem-h** [comment] 2016-09-29 12:23
@johnmcaliley  Its works , thank you 
Please merge it with master brunch

**Comment by pablougas** [comment] 2016-10-04 20:30
Is it possible that the latest update might've broken something in rails 4.2? my system says that it hasn't logged any impressions since 9/19?

**Comment by Qasem-h** [comment] 2016-11-12 22:42
@johnmcaliley please release new version

**Comment by uzaif313** [comment] 2016-12-07 07:41
thanks  @johnmcaliley  its work now after

**Comment by dtelaroli** [comment] 2016-12-21 18:57
:+1:

**Comment by alexander-alyoshin** [comment] 2017-01-14 01:33
@johnmcaliley **+1**

**Comment by jgrau** [comment] 2017-05-25 07:11
Rails 5 support has been added in v1.6.0
The problem with the missing column `params` has been described in an [upgrade guide](https://github.com/charlotte-ruby/impressionist/blob/master/UPGRADE_GUIDE.md)

**Closed by jgrau** 2017-05-25 07:11 UTC
